//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluemixDeployment {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.eu-gb.bluemix.net")]
        public string UrlCloud {
            get {
                return ((string)(this["UrlCloud"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"eyJhbGciOiJIUzI1NiIsImtpZCI6ImtleS0xIiwidHlwIjoiSldUIn0.eyJqdGkiOiJlZWJhYmViYjIxNDc0ODM0YTcyMDkyMTgwYThlNzMyMCIsInN1YiI6IjNhMDMyNzlmLTY4MjctNGUxZi1hOGYzLWU4ODM3NDg1MDEwZSIsInNjb3BlIjpbIm9wZW5pZCIsInVhYS51c2VyIiwiY2xvdWRfY29udHJvbGxlci5yZWFkIiwicGFzc3dvcmQud3JpdGUiLCJjbG91ZF9jb250cm9sbGVyLndyaXRlIl0sImNsaWVudF9pZCI6ImNmIiwiY2lkIjoiY2YiLCJhenAiOiJjZiIsImdyYW50X3R5cGUiOiJwYXNzd29yZCIsInVzZXJfaWQiOiIzYTAzMjc5Zi02ODI3LTRlMWYtYThmMy1lODgzNzQ4NTAxMGUiLCJvcmlnaW4iOiJ1YWEiLCJ1c2VyX25hbWUiOiJwb3ViaGl4LTY5QHlhaG9vLmZyIiwiZW1haWwiOiJwb3ViaGl4LTY5QHlhaG9vLmZyIiwiYXV0aF90aW1lIjoxNTA2MjA5NTM1LCJyZXZfc2lnIjoiMjI1NDRkMjQiLCJpYXQiOjE1MDYyMDk1MzUsImV4cCI6MTUwNzQxOTEzNSwiaXNzIjoiaHR0cHM6Ly91YWEubmcuYmx1ZW1peC5uZXQvb2F1dGgvdG9rZW4iLCJ6aWQiOiJ1YWEiLCJhdWQiOlsiY2xvdWRfY29udHJvbGxlciIsInBhc3N3b3JkIiwiY2YiLCJ1YWEiLCJvcGVuaWQiXX0.IHn0r8u6joHiNWNmMSzeLlcoTfXkgsJbFkzDrueUTbo")]
        public string Token {
            get {
                return ((string)(this["Token"]));
            }
        }
    }
}
